#pragma once

#include "./Assets/ClipMap.hpp"
#include "./Assets/ComWorld.hpp"
#include "./Assets/FxEffectDef.hpp"
#include "./Assets/FxWorld.hpp"
#include "./Assets/GfxImage.hpp"
#include "./Assets/GfxLightDef.hpp"
#include "./Assets/GfxWorld.hpp"
#include "./Assets/GlassWorld.hpp"
#include "./Assets/MapEnts.hpp"
#include "./Assets/PhysPreset.hpp"
#include "./Assets/RawFile.hpp"
#include "./Assets/Sound.hpp"
#include "./Assets/SoundCurve.hpp"
#include "./Assets/XAnimParts.hpp"
#include "./Assets/XModel.hpp"
#include "./Assets/XSurface.hpp"